// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCChJCX7gK1OvWwaYu0NlbItxMjuzKF_A8',
    appId: '1:182812771513:web:3f3a01a87b02bdc0f10768',
    messagingSenderId: '182812771513',
    projectId: 'tadbiro-by-parviz',
    authDomain: 'tadbiro-by-parviz.firebaseapp.com',
    storageBucket: 'tadbiro-by-parviz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDyJXIXGEhMW7uJg9Carm6IMRIvwDmXa8',
    appId: '1:182812771513:android:8d3724bd3b0c01a3f10768',
    messagingSenderId: '182812771513',
    projectId: 'tadbiro-by-parviz',
    storageBucket: 'tadbiro-by-parviz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClzXsACp36DvuJQSZDnHJOeSPWlHS0j4U',
    appId: '1:182812771513:ios:73fc85f0e76f220ff10768',
    messagingSenderId: '182812771513',
    projectId: 'tadbiro-by-parviz',
    storageBucket: 'tadbiro-by-parviz.appspot.com',
    iosBundleId: 'com.example.tadbiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClzXsACp36DvuJQSZDnHJOeSPWlHS0j4U',
    appId: '1:182812771513:ios:73fc85f0e76f220ff10768',
    messagingSenderId: '182812771513',
    projectId: 'tadbiro-by-parviz',
    storageBucket: 'tadbiro-by-parviz.appspot.com',
    iosBundleId: 'com.example.tadbiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCChJCX7gK1OvWwaYu0NlbItxMjuzKF_A8',
    appId: '1:182812771513:web:80397f04423b150cf10768',
    messagingSenderId: '182812771513',
    projectId: 'tadbiro-by-parviz',
    authDomain: 'tadbiro-by-parviz.firebaseapp.com',
    storageBucket: 'tadbiro-by-parviz.appspot.com',
  );
}
